# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt:
        sources: 
            - deadsnakes
        packages:
            - lib32stdc++6
            # We need at least python3.7 to run our custom deployment scripts
            - python3.7

# Set the build environment
env:
    global:
        - TR_COMP_STABLE_VERSION="1.8"
        #UPDATER_REPO_OAUTH
        - secure: "WtXF+/fPglmoDnI1l0fGnUmC8zrYxaaHdpG3IwKD95o/hUnSk4L0kfFvxhqDIqmhZOAFpdERnmpo1IrdR/LoTO5htO+5qZ+fmaDh5He7EbaNAaafOVaDKJ4GTj+HPYah8gVodvkzKOOqi5fnGekaKa9Fv8G0WEDcikIJ59HQ6yaGx6Jh/ct7G7OfY1nGhvj5frSBGK4PiPvtuC8w1GOvzamRGAebQ7BZzHcr50TvA8WzsSb/wcPdhRKbb0Q85E0L6ndXVt7pTYtzhFq84LIQTCjYWV3126+fjehoCK8V4isFqwYcrISft6UTpEGJ7U2J4V7h7lvxuqOZG6+m+sKPm8QIsopeiHPLOin7X+ye50k/Hhdkw2YS+x4hQBYntW6loop0gfNxb7OCy+P3dZxmExlc2yH/lLX0rcPStdP7f0hcj4RT3yH4e467ZvW2UI0V0YlQvMUpQeOPEGLfTBw4zd2hdwY7WSjf8y0DN7ThZ2Rf62pIMTW3fBzp6NmVXaik7vd/ryvx0kmjih8HNxuO46SUfcMfpNyHwL2QRUbp1mPiVk2pJzaehhYGLRxI2z6XJ+3/+S/UzGWz/d+D8pvbWqKcNLLyh8B1el/nQ40OQQoQipWjudHRBryy4JcNDbDPKAqC7cW10AENTl1P8TOQAQsURyiHaISrhvRK53TX7PQ="
    matrix:
        - TR_COMP_VERSION=1.8 TR_RELEASE_CACHE_BUILDER=tf2idb
        - TR_COMP_VERSION=1.8 TR_RELEASE_CACHE_BUILDER=tf2ii
        - TR_COMP_VERSION=1.9 TR_RELEASE_CACHE_BUILDER=tf2idb
        - TR_COMP_VERSION=1.9 TR_RELEASE_CACHE_BUILDER=tf2ii

# Allow the experimental branch to fail
matrix:
    fast_finish: true
    allow_failures:
        - env: TR_COMP_VERSION=1.9

install:
    - TR_PROJECT_ROOT="$TRAVIS_BUILD_DIR"
    - TR_PACKAGE_DIR="$TR_PROJECT_ROOT/.package" && mkdir "$TR_PACKAGE_DIR"
    - TR_SM_DIR="$TR_PACKAGE_DIR/smdrop" && mkdir "$TR_SM_DIR"
    - TR_SM_URL="http://sourcemod.net/smdrop/$TR_COMP_VERSION"

    # Downloading and extracting SourceMod
    - TR_SM_RELEASE="$(wget "$TR_SM_URL/sourcemod-latest-linux" -qO-)"
    - wget -qO- "$TR_SM_URL/$TR_SM_RELEASE" | tar -xz -C "$TR_SM_DIR"
    - TR_SM_SCRIPTING_DIR="$TR_SM_DIR/addons/sourcemod/scripting"
    - chmod +x "$TR_SM_SCRIPTING_DIR/spcomp"
    
    - TR_PROJECT_INCLUDE_DIR="$TR_PROJECT_ROOT/scripting/include"
    # Downloading includes
    - wget https://raw.githubusercontent.com/asherkin/TF2Items/d81b0ff7e98b197431ff13f1a16a6989c5ae2032/pawn/tf2items.inc -O "$TR_PROJECT_INCLUDE_DIR/tf2items.inc"
    - wget https://raw.githubusercontent.com/chauffer/tf2itemsinfo/5db9765ea8cb6c6c32276b08fdb2d8c13385b067/scripting/include/tf2itemsinfo.inc -O "$TR_PROJECT_INCLUDE_DIR/tf2itemsinfo.inc"
    - wget https://raw.githubusercontent.com/FlaminSarge/tf2idb/c2bc42e34c2a2e9a4e9ad0d0fe8cda564e970bb6/scripting/include/tf2idb.inc -O "$TR_PROJECT_INCLUDE_DIR/tf2idb.inc"
    - wget https://bitbucket.org/GoD_Tony/updater/raw/12181277db77d6117052b8ddf5810c7681745156/include/updater.inc -O "$TR_PROJECT_INCLUDE_DIR/updater.inc"
    
    - |
      if [[ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]]; then
          TR_RELEASE_REAL_BRANCH="master"
      else
          TR_RELEASE_REAL_BRANCH="$TRAVIS_BRANCH"
      fi
    
# And build!
script: 
    - |
      (
          cd "$TR_PACKAGE_DIR" && 
          python3.7 "$TR_PROJECT_ROOT/build.py" \
              --smlib "$TR_SM_SCRIPTING_DIR" \
              --item_schema_api "$TR_RELEASE_CACHE_BUILDER" \
              --branch "$TR_RELEASE_REAL_BRANCH" \
      )

before_deploy:
    - TR_PACKAGE_BUILD_DIR="$TR_PACKAGE_DIR/build-$TR_RELEASE_CACHE_BUILDER"
    - TR_PACKAGE_ROOT_DIR="$TR_PACKAGE_BUILD_DIR/root"
    - TR_GH_DEPLOY_ARGS_FILE="$TR_PACKAGE_BUILD_DIR/gh_deploy_args.txt"
    - |
      if [[ -f "$TR_GH_DEPLOY_ARGS_FILE"  && '"$TR_COMP_VERSION" == "$TR_COMP_STABLE_VERSION"' ]]; then
          TR_GH_DEPLOY=0
          ln -s "$TR_PACKAGE_ROOT_DIR" "$TR_PACKAGE_BUILD_DIR/.package_updater"
          TR_GH_DEPLOY_SCRIPT="$TR_PROJECT_ROOT/buildtools/scripts/tony_updater/deploy.sh"
          chmod +x "$TR_GH_DEPLOY_SCRIPT"
          mapfile -t TR_GH_DEPLOY_ARGS <"$TR_GH_DEPLOY_ARGS_FILE"
          TR_RELEASE_NAME="${TR_GH_DEPLOY_ARGS[0]}"
          TR_RELEASE_VERSION="${TR_GH_DEPLOY_ARGS[1]}"
          TR_UPDATER_REPO="${TR_GH_DEPLOY_ARGS[2]}"
          TR_UPDATER_USER="${TR_GH_DEPLOY_ARGS[3]}"
          TR_UPDATER_BRANCH="${TR_GH_DEPLOY_ARGS[4]}"
      else
          TR_GH_DEPLOY=1
      fi

deploy:
    - provider: releases
      api_key:
          secure: cfmiJb0kZfusm8RU2CJmKvDQPByXPqA1YxKeGCOnJlXY55pvJwMB+iqGW5zmxAOfv4x9H4LAdUstc7TOnGtw06hqrOEPsUTIo58uZqnZbNI6VyhMajdTHrLe/FPLeUbPu4f4AVU9KuSgi/td+6yzXuyQ4ZjFJoZYwBWKAmNGKEv2QQgSIKA0/BxsAfSQEHkwJd27HrRjwWdvCIF7oEDf2TAFdYOt9CvAgj7ARsW4st6z7aRf9TmGb3yEUkTm3JkU/LIVK6t77+o4X7MVorgDD6f7QWIzyjVFg/A9tkYOK/xIn2TXj82y2cvEzQGT9aKsHWt/IHWnSJej6DvBwP+dZEVGQHvVn2GfEJXAyrT+jacPWpbC8FOddiw/SSQFfACI8s6F52koNpSDxJmeihPc0Kynk46o/fed/Vg5Mb+hKl8CNJvee5Izsxty+mYVQoK+aHrXZPyPbm4WbeL+chGoU3O36VbFvTXMA5fN+Ot4vwGsxutXbImva8IHYmW5LNT+2d1Z57sbGf0bgEjeozE8shHHQwHECVLRGIXmzYtoWFjvtmLbt2CC9vYjooKjQv7+wjGSrya2u61rWC8w2BaJnzdguXroU+0TaIdzdDrC85r9VttcvEOWNLROTf+7Fgxq/dAyvfyz3pw2Noh8zyr3RUrXfLWhCLagLoeZ93agNUY=
      file: '"$TR_PACKAGE_BUILD_DIR/*.zip"'
      skip_cleanup: true
      on:
          #only deploy for the stable branch
          condition: '"$TR_COMP_VERSION" == "$TR_COMP_STABLE_VERSION"'
          repo: fakuivan/TF2-Taunts-TF2IDB
          branch: master
          tags: true
        
    - provider: script
      script: 
              'cd "$TR_PACKAGE_BUILD_DIR" &&
              "$TR_GH_DEPLOY_SCRIPT"
                  "$TR_RELEASE_NAME"
                  "$TR_RELEASE_VERSION"
                  "$TR_UPDATER_REPO"
                  "$TR_UPDATER_USER"
                  "$UPDATER_REPO_OAUTH"
                  "fakuivan"
                  "fakuivan@gmail.com"
                  "$TR_UPDATER_BRANCH"'
      skip_cleanup: true
      on:
          repo: fakuivan/TF2-Taunts-TF2IDB

          condition: '"$TR_GH_DEPLOY" == 0'
          tags: false

# Notifications
notifications:
    email: false
